import { useChatStore } from '@/stores/chat'
import { useRoleStore } from '@/stores/role'
import { useDocumentStore } from '@/stores/document'
import { sendMessage, generateAllDocuments } from '@/services/ai.service'
import { useError } from '@/composables/useError'
import type { Document } from '@/types'

export function useChat() {
  const chatStore = useChatStore()
  const roleStore = useRoleStore()
  const docStore = useDocumentStore()
  const { errorMsg, setError } = useError()

  async function sendMessageAndReply(content: string) {
    console.log('[Chat] 用户发送:', content.slice(0, 50))

    await chatStore.addMessage('user', content)
    chatStore.generating = true
    chatStore.streamingContent = ''

    try {
      const role = roleStore.getCurrentRole()
      console.log('[Chat] 当前角色:', role?.name ?? '(无)')

      const result = await sendMessage(
        chatStore.messages,
        role,
        (text) => { chatStore.streamingContent = text },
      )
      await chatStore.addMessage('assistant', result)
      chatStore.generating = false
      chatStore.streamingContent = ''
      console.log('[Chat] 回复已保存')

      autoGenerateDocs()
    } catch (e: any) {
      chatStore.generating = false
      chatStore.streamingContent = ''
      console.error('[Chat] 发送失败:', e)
      setError(e?.message ?? '发送失败', 8000)
    }
  }

  async function autoGenerateDocs() {
    if (!chatStore.currentSessionId || !chatStore.messages.length) return

    docStore.generating = true
    try {
      const role = roleStore.getCurrentRole()
      const { useSettingsStore } = await import('@/stores/settings')
      const emotions = useSettingsStore().settings.defaultEmotions
      console.log('[Chat] 自动生成文档, 情绪数:', emotions.length)

      const results = await generateAllDocuments(chatStore.messages, emotions, role)

      const docs: Omit<Document, 'id' | 'createdAt'>[] = []
      for (const r of results) {
        if ('result' in r) {
          docs.push({
            sessionId: chatStore.currentSessionId,
            emotion: r.emotion,
            title: r.result.title,
            content: r.result.content,
            status: 'pending',
          })
        }
      }

      if (docs.length) {
        await docStore.addDocuments(docs)
      }

      const failed = results.filter(r => 'error' in r)
      if (failed.length) {
        setError(`${failed.length} 种情绪文档生成失败`, 5000)
      }

      console.log('[Chat] 文档生成完成, 成功:', docs.length, '失败:', failed.length)
    } catch (e: any) {
      console.error('[Chat] 文档生成异常:', e)
      setError(e?.message ?? '文档生成失败', 5000)
    } finally {
      docStore.generating = false
    }
  }

  return {
    chatStore,
    docStore,
    errorMsg,
    sendMessageAndReply,
  }
}