import { useChatStore } from '@/stores/chat'
import { useDocumentStore } from '@/stores/document'
import { sendMessage, generateMainLink, generateSummaryDocs, generateTitle } from '@/services/ai.service'
import { useError } from '@/composables/useError'
import type { Document } from '@/types'

export function useChat() {
  const chatStore = useChatStore()
  const docStore = useDocumentStore()
  const { errorMsg, setError } = useError()

  async function sendMessageAndReply(content: string) {
    if (!chatStore.currentSessionId) {
      await chatStore.createSession()
    }

    // 等待 Main_link 生成完成，避免读到旧值（重新选文件夹后会触发自动刷新）
    if (chatStore.generatingMainLink) {
      console.log('[Chat] 等待 Main_link 生成完成...')
      while (chatStore.generatingMainLink) {
        await new Promise(r => setTimeout(r, 100))
      }
    }

    const sessionId = chatStore.currentSessionId
    const session = chatStore.currentSession
    const mainLink = session?.mainLinkContent ?? ''

    console.log('[Chat] 用户发送:', content.slice(0, 50), 'Main_link:', mainLink ? `(${mainLink.length}字, 前缀: ${mainLink.slice(0, 30)})` : '(无)')

    await chatStore.addMessage('user', content)
    if (chatStore.messages.length === 1 && session) {
      const title = content.trim().slice(0, 10) + (content.length > 10 ? '...' : '')
      await chatStore.updateTitle(sessionId!, title)
    }
    chatStore.generating = true
    chatStore.streamingContent = ''

    try {
      const result = await sendMessage(
        chatStore.messages,
        mainLink,
        (text) => { chatStore.streamingContent = text },
      )
      await chatStore.addMessage('assistant', result)
      chatStore.generating = false
      chatStore.streamingContent = ''
      console.log('[Chat] 回复已保存')

      autoGenerateDocs()
    } catch (e: any) {
      chatStore.generating = false
      chatStore.streamingContent = ''
      console.error('[Chat] 发送失败:', e)
      setError(e?.message ?? '发送失败', 8000)
    }
  }

  async function generateMainLinkForCurrentSession(silent = false) {
    if (!chatStore.currentSessionId) {
      if (silent) return
      await chatStore.createSession()
    }
    const session = chatStore.currentSession
    if (!session) {
      if (!silent) setError('无法获取当前会话', 5000)
      return
    }

    console.log('[MainLink] 当前会话:', session.id, '选中文件夹:', session.selectedFolderIds)

    if (!session.selectedFolderIds.length) {
      if (session.mainLinkContent) await chatStore.updateMainLink(session.id, '')
      console.log('[MainLink] 未勾选文件夹，Main_link 已清空')
      return
    }

    chatStore.generatingMainLink = true
    try {
      const docs = await docStore.getDocsByFolders(session.selectedFolderIds)
      console.log('[MainLink] 文件夹内文档数:', docs.length)
      if (!docs.length) {
        if (session.mainLinkContent) await chatStore.updateMainLink(session.id, '')
        console.log('[MainLink] 文件夹无文档，Main_link 已清空')
        return
      }

      const content = await generateMainLink(docs)
      if (!content) {
        if (!silent) setError('Main_link 生成返回空内容', 5000)
        return
      }

      await chatStore.updateMainLink(session.id, content)
      console.log('[MainLink] 自动刷新完成, 字数:', content.length)
    } catch (e: any) {
      console.error('[MainLink] 生成失败:', e)
      if (!silent) setError(e?.message ?? 'Main_link 生成失败', 8000)
    } finally {
      chatStore.generatingMainLink = false
    }
  }

  async function autoGenerateDocs() {
    if (!chatStore.currentSessionId || !chatStore.messages.length) return

    docStore.generating = true
    try {
      console.log('[Chat] 自动提炼小文档')
      const results = await generateSummaryDocs(chatStore.messages)

      const docs: Omit<Document, 'id' | 'createdAt'>[] = results.map(r => ({
        sessionId: chatStore.currentSessionId,
        folderIds: [],
        theme: r.theme || '其它',
        title: r.title,
        content: r.content,
        status: 'pending',
      }))

      if (docs.length) {
        await docStore.addDocuments(docs)
        try {
          const title = await generateTitle(docs)
          if (title && chatStore.currentSessionId) {
            await chatStore.updateTitle(chatStore.currentSessionId, title)
            console.log('[Chat] 会话标题已更新:', title)
          }
        } catch (e) {
          console.error('[Chat] 标题生成失败:', e)
        }
      }

      console.log('[Chat] 小文档生成完成, 数量:', docs.length)
    } catch (e: any) {
      console.error('[Chat] 小文档生成异常:', e)
      setError(e?.message ?? '小文档生成失败', 5000)
    } finally {
      docStore.generating = false
    }
  }

  function autoRefreshMainLink() {
    generateMainLinkForCurrentSession(true)
  }

  async function toggleFolderSelection(folderId: string) {
    if (!chatStore.currentSessionId) {
      await chatStore.createSession()
    }
    const session = chatStore.currentSession
    if (!session) return

    const ids = [...session.selectedFolderIds]
    const idx = ids.indexOf(folderId)
    if (idx >= 0) {
      ids.splice(idx, 1)
    } else {
      ids.push(folderId)
    }
    await chatStore.setSelectedFolderIds(session.id, ids)
  }

  return {
    chatStore,
    docStore,
    errorMsg,
    sendMessageAndReply,
    generateMainLinkForCurrentSession,
    autoRefreshMainLink,
    toggleFolderSelection,
  }
}
